
-- Insert sample love messages
INSERT INTO love_messages (author_name, message, pet_name, pet_type, is_approved, created_at, updated_at) VALUES
('Maria Silva', 'O Clube dos Bichos é incrível! Minha Mel sempre fica linda depois do banho e tosa. A equipe é super carinhosa e profissional. Recomendo para todos!', 'Mel', 'Cachorro', 1, datetime('now', '-10 days'), datetime('now', '-10 days')),
('João Santos', 'Encontrei no Clube dos Bichos exatamente o que procurava: cuidado com amor! Meu Thor adora ir lá, e eu fico tranquilo sabendo que ele está em boas mãos.', 'Thor', 'Cachorro', 1, datetime('now', '-8 days'), datetime('now', '-8 days')),
('Ana Paula', 'Minha gata Luna é muito medrosa, mas no Clube dos Bichos ela se sente em casa. O Dr. Carlos e toda equipe são fantásticos! Muito obrigada pelo carinho.', 'Luna', 'Gato', 1, datetime('now', '-6 days'), datetime('now', '-6 days')),
('Carlos Mendes', 'Atendimento excepcional! Meu Buddy chegou sujo e saiu um príncipe. Além disso, descobriram um probleminha de pele que outros não viram. Salvaram meu pet!', 'Buddy', 'Cachorro', 1, datetime('now', '-4 days'), datetime('now', '-4 days')),
('Fernanda Costa', 'O Clube dos Bichos é mais que um petshop, é uma família! Cuidam do meu Max com tanto amor que fico emocionada. Parabéns pela dedicação!', 'Max', 'Cachorro', 1, datetime('now', '-2 days'), datetime('now', '-2 days'));

-- Insert sample products
INSERT INTO products (name, description, price, image_url, category, is_available, created_at, updated_at) VALUES
('Ração Royal Canin Medium Adult', 'Alimento completo e balanceado para cães adultos de porte médio. Fórmula desenvolvida especialmente para as necessidades nutricionais.', 'R$ 189,90', 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=300&h=300&fit=crop', 'food', 1, datetime('now'), datetime('now')),
('Brinquedo Kong Classic Vermelho', 'Brinquedo indestrutível feito de borracha natural. Perfeito para cães que gostam de mastigar e brincar.', 'R$ 45,90', 'https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=300&h=300&fit=crop', 'toys', 1, datetime('now'), datetime('now')),
('Coleira Antipulgas Seresto Bayer', 'Proteção contínua contra pulgas e carrapatos por até 8 meses. Resistente à água e sem odor.', 'R$ 159,90', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=300&h=300&fit=crop', 'health', 1, datetime('now'), datetime('now')),
('Shampoo Pet Clean Neutro', 'Shampoo hipoalergênico para peles sensíveis. Fórmula suave que limpa sem ressecar a pele.', 'R$ 24,90', 'https://images.unsplash.com/photo-1608096299210-db7e38487075?w=300&h=300&fit=crop', 'hygiene', 1, datetime('now'), datetime('now')),
('Cama Ortopédica Memory Foam G', 'Cama super confortável com espuma viscoelástica. Ideal para cães idosos ou com problemas articulares.', 'R$ 299,90', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=300&h=300&fit=crop', 'accessories', 1, datetime('now'), datetime('now')),
('Petisco Natural Ossinho Bovino', 'Osso natural 100% bovino para limpeza dos dentes. Rico em cálcio e fósforo.', 'R$ 12,90', 'https://images.unsplash.com/photo-1605244863941-3a6c50f0b2a8?w=300&h=300&fit=crop', 'food', 1, datetime('now'), datetime('now')),
('Arranhador Gigante para Gatos', 'Torre arranhador com múltiplos níveis. Perfeita para gatos brincarem e afiarem as unhas.', 'R$ 189,90', 'https://images.unsplash.com/photo-1574144611937-0df059b5ef3e?w=300&h=300&fit=crop', 'toys', 1, datetime('now'), datetime('now')),
('Ração Hills Science Diet Felino', 'Nutrição científica para gatos adultos. Fórmula balanceada para manutenção da saúde.', 'R$ 129,90', 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=300&h=300&fit=crop', 'food', 1, datetime('now'), datetime('now'));

-- Insert sample services
INSERT INTO services (name, description, price, duration, image_url, category, is_available, created_at, updated_at) VALUES
('Banho Completo', 'Banho relaxante com produtos premium, secagem profissional, corte de unhas e limpeza de ouvidos. Inclui perfume canino.', 'A partir de R$ 35', '45-60 min', 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&h=300&fit=crop', 'grooming', 1, datetime('now'), datetime('now')),
('Tosa Higiênica', 'Corte nas áreas íntimas, patas e orelhas para manter a higiene e conforto do seu pet. Essencial para a saúde.', 'A partir de R$ 25', '30-45 min', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop', 'grooming', 1, datetime('now'), datetime('now')),
('Tosa Completa Criativa', 'Corte personalizado seguindo o padrão da raça ou criativo conforme preferência. Inclui banho e acabamento.', 'A partir de R$ 65', '90-120 min', 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=300&fit=crop', 'grooming', 1, datetime('now'), datetime('now')),
('Consulta Veterinária', 'Avaliação completa da saúde do seu pet com veterinário especializado. Inclui exame físico detalhado.', 'A partir de R$ 80', '30-45 min', 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=400&h=300&fit=crop', 'veterinary', 1, datetime('now'), datetime('now')),
('Vacinação Completa', 'Aplicação de vacinas essenciais (V8, V10, antirrábica). Inclui carteira de vacinação atualizada.', 'A partir de R$ 60', '15-20 min', 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=300&fit=crop', 'veterinary', 1, datetime('now'), datetime('now')),
('Plano Mensal Básico', '2 banhos completos + 1 tosa higiênica + 10% desconto em produtos. Ideal para manutenção regular.', 'R$ 89/mês', 'Mensal', 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&h=300&fit=crop', 'plans', 1, datetime('now'), datetime('now')),
('Plano Mensal Premium', '3 banhos + 1 tosa completa + 1 consulta veterinária + 20% desconto em produtos. Cuidado completo.', 'R$ 149/mês', 'Mensal', 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&h=300&fit=crop', 'plans', 1, datetime('now'), datetime('now')),
('Atendimento Domiciliar', 'Banho e tosa na comodidade da sua casa. Ideal para pets idosos ou com dificuldade de locomoção.', 'A partir de R$ 120', '60-90 min', 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&h=300&fit=crop', 'grooming', 1, datetime('now'), datetime('now'));
